### ISSUE TITLE
Pre Solidity audit checklist

### ISSUE THREAD

**Issue by RnkSngh** [open-ibc/vibc-core-smart-contracts#93]
- [x]  Add Apache 2.0 license to vibc-core repo (can use similar to ibc-sdk repo)
- [x] Implement all changes requested by informal
- [x] Clear timeout implementation - make it an empty api simialr to ch close 
- [x] fix OZ library import -> change Dispatcher's inheritance from `ReentrancyGuard` to `ReentrancyGuardUpgradeable`
- [ ] Run through the [attack vectors identified by informal systems ](https://docs.google.com/document/d/14mh6cxPNsP2NWyQi9-dKrBJoWnkIlkhL3_A5cZtgSU8/edit)
- [x] re-read through of all natspec and documentation
- [x] access control + visibility check of all functions
